### ISSUE TITLE
fallback isn't used in backable_back_path

### ISSUE THREAD

**Issue by seliverstov-maxim** [gamecreature/backable#1]
![image](https://user-images.githubusercontent.com/4324963/51895613-02db4f00-23c4-11e9-844d-54827c1b8d5e.png)

**Comment by seliverstov-maxim** [comment]
Moreover, I would like to have opportunity to configure a default back path.

**Comment by gamecreature** [comment]
This has been fixed:
```ruby
Backable.fallback_url = "/new-path"
```
